# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('t', 'timer'), ('sw', 'stopwatch')], default='sw', max_length=2)),
            ],
        ),
    ]
